/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package courseenrollmentsystem;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dilsha Hettiarachchi
 */
public class SubjectSelection1 extends javax.swing.JFrame {

    DBOperations dbOps =new DBOperations();
    /**
     * Creates new form SubjectSelection1
     */
    public SubjectSelection1() {
        initComponents();
    }

    void addOptionalSubject(int n, int y, int s,String t) {

        int i = 0;
        String[] cmb = dbOps.fillOptionalSubjectCombo(n, y, s,t);
        while (i < cmb.length) {
            ddSub1.addItem(cmb[i]);
            ddSub2.addItem(cmb[i]);
            ddSub3.addItem(cmb[i]);
            ddSub4.addItem(cmb[i]);
            i++;
        }
    }

    void setOptional(SelectedSubject selSub) {
        ddSub1.setSelectedItem(selSub.getSub1());
        ddSub2.setSelectedItem(selSub.getSub2());
        ddSub3.setSelectedItem(selSub.getSub3());
        ddSub4.setSelectedItem(selSub.getSub4());
    }

    void loadSelectedSubject(int regNo, int year, int semester,String cType) {
        SelectedSubject s = new SelectedSubject();
        s = dbOps.getSelectedSubject(regNo, year, semester,cType);
        setOptional(s);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ddYear = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ddSemester = new javax.swing.JComboBox<>();
        btnGo = new javax.swing.JButton();
        txtReg = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ddSub1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        ddSub3 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ddSub2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        ddSub4 = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        btnT = new javax.swing.JButton();
        txtT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Optional Subjects", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student Reg No");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Year");

        ddYear.setBackground(new java.awt.Color(108, 122, 137));
        ddYear.setForeground(new java.awt.Color(255, 255, 255));
        ddYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Semester");

        ddSemester.setBackground(new java.awt.Color(108, 122, 137));
        ddSemester.setForeground(new java.awt.Color(255, 255, 255));
        ddSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        btnGo.setBackground(new java.awt.Color(37, 116, 169));
        btnGo.setForeground(new java.awt.Color(255, 255, 255));
        btnGo.setText("Go");
        btnGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoActionPerformed(evt);
            }
        });

        txtReg.setBackground(new java.awt.Color(108, 122, 137));
        txtReg.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtReg, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ddYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(ddSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(btnGo)
                .addGap(38, 38, 38))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(ddYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(ddSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGo)
                    .addComponent(txtReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Subject 1");

        ddSub1.setBackground(new java.awt.Color(108, 122, 137));
        ddSub1.setForeground(new java.awt.Color(255, 255, 255));
        ddSub1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Subject 3");

        ddSub3.setBackground(new java.awt.Color(108, 122, 137));
        ddSub3.setForeground(new java.awt.Color(255, 255, 255));
        ddSub3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Subject 2");

        ddSub2.setBackground(new java.awt.Color(108, 122, 137));
        ddSub2.setForeground(new java.awt.Color(255, 255, 255));
        ddSub2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Subject 4");

        ddSub4.setBackground(new java.awt.Color(108, 122, 137));
        ddSub4.setForeground(new java.awt.Color(255, 255, 255));
        ddSub4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ddSub1, 0, 180, Short.MAX_VALUE)
                    .addComponent(ddSub3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ddSub2, 0, 180, Short.MAX_VALUE)
                    .addComponent(ddSub4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ddSub1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(ddSub2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(ddSub4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ddSub3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        btnSubmit.setBackground(new java.awt.Color(37, 116, 169));
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnT.setBackground(new java.awt.Color(37, 116, 169));
        btnT.setForeground(new java.awt.Color(255, 255, 255));
        btnT.setText("Get Total Credits");
        btnT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTActionPerformed(evt);
            }
        });

        txtT.setBackground(new java.awt.Color(108, 122, 137));
        txtT.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(btnT)
                .addGap(32, 32, 32)
                .addComponent(txtT, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnT)
                    .addComponent(txtT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoActionPerformed
        if (dbOps.checkOptionalAdded((Integer.parseInt(txtReg.getText())), (Integer.parseInt(ddYear.getSelectedItem().toString())), (Integer.parseInt(ddSemester.getSelectedItem().toString())),"Master")) {
            int yesOrNo = JOptionPane.showConfirmDialog(null, "Already added optional subjects for this student. Do you want to change optional subjects?", "Update Optional Subjects", JOptionPane.YES_NO_OPTION);
            if (yesOrNo == 0) {
                ddSub1.removeAllItems();
                ddSub2.removeAllItems();
                ddSub3.removeAllItems();
                ddSub4.removeAllItems();
                addOptionalSubject((Integer.parseInt(txtReg.getText())), (Integer.parseInt(ddYear.getSelectedItem().toString())), (Integer.parseInt(ddSemester.getSelectedItem().toString())),"poststudent");
                loadSelectedSubject((Integer.parseInt(txtReg.getText())), (Integer.parseInt(ddYear.getSelectedItem().toString())), (Integer.parseInt(ddSemester.getSelectedItem().toString())),"Master");
            } else if (yesOrNo == 1) {
                //clearFields();
                txtReg.setText("");

            }
        } else {
            ddSub1.removeAllItems();
            ddSub2.removeAllItems();
            ddSub3.removeAllItems();
            ddSub4.removeAllItems();
            addOptionalSubject((Integer.parseInt(txtReg.getText())), (Integer.parseInt(ddYear.getSelectedItem().toString())), (Integer.parseInt(ddSemester.getSelectedItem().toString())),"poststudent");
        }
    }//GEN-LAST:event_btnGoActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        int t = getTotalCredits();
        if (t >= 4) {
            SelectedSubject selSub = new SelectedSubject();
            selSub.setRegNo(Integer.parseInt(txtReg.getText()));
            selSub.setYear(Integer.parseInt(ddYear.getSelectedItem().toString()));
            selSub.setSemester(Integer.parseInt(ddSemester.getSelectedItem().toString()));
            selSub.setCType("Master");
            selSub.setSub1(ddSub1.getSelectedItem().toString());
            selSub.setSub2(ddSub2.getSelectedItem().toString());
            selSub.setSub3(ddSub3.getSelectedItem().toString());
            selSub.setSub4(ddSub4.getSelectedItem().toString());

            if (dbOps.checkOptionalAdded((Integer.parseInt(txtReg.getText())), (Integer.parseInt(ddYear.getSelectedItem().toString())), (Integer.parseInt(ddSemester.getSelectedItem().toString())),"Master")) {
                if (dbOps.updateSelectedSubject(selSub)) {
                    JOptionPane.showMessageDialog(this, "Successfully updated the optional subjects !!");

                } else {
                    JOptionPane.showMessageDialog(this, "Error while Updating !!");
                    this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                }
            } else {
                if (dbOps.addSelectedSubject(selSub)) {
                    JOptionPane.showMessageDialog(this, "Successfully inserted the optional subjects!!");
                    //clearFields();

                } else {
                    JOptionPane.showMessageDialog(this, "Error while inserting !!");
                    this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Total credit value is not enough. Go to an another selection!!");
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTActionPerformed
        int t = getTotalCredits();
        txtT.setText(new Integer(t).toString());
    }//GEN-LAST:event_btnTActionPerformed

    int getTotalCredits() {
        int c1, c2, c3, c4, t;
        c1 = dbOps.getCreditValue(ddSub1.getSelectedItem().toString());
        c2 = dbOps.getCreditValue(ddSub2.getSelectedItem().toString());
        c3 = dbOps.getCreditValue(ddSub3.getSelectedItem().toString());
        c4 = dbOps.getCreditValue(ddSub4.getSelectedItem().toString());
        t = c1 + c2 + c3 + c4;
        return t;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SubjectSelection1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SubjectSelection1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SubjectSelection1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SubjectSelection1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SubjectSelection1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGo;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnT;
    private javax.swing.JComboBox<String> ddSemester;
    private javax.swing.JComboBox<String> ddSub1;
    private javax.swing.JComboBox<String> ddSub2;
    private javax.swing.JComboBox<String> ddSub3;
    private javax.swing.JComboBox<String> ddSub4;
    private javax.swing.JComboBox<String> ddYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtReg;
    private javax.swing.JTextField txtT;
    // End of variables declaration//GEN-END:variables
}
